version: '3'

services:
  db:
    image: mysql:8.0
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - vue_wp

  wordpress:
    build:
      context: ./.docker/wp
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8080:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    volumes:
      - ./wordpress:/var/www/html
    networks:
      - vue_wp

  front:
    build:
      context: ./.docker/front
      dockerfile: Dockerfile
    volumes:
      - ./front:/usr/src/app
    stdin_open: true
    command: yarn dev
    tty: true
    ports:
      - "5173:5173"
    networks:
      - vue_wp

volumes:
  db_data:

networks:
  vue_wp:
    driver: bridge